version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ab-conference-db
    environment:
      POSTGRES_DB: conference_manager
      POSTGRES_USER: conference_user
      POSTGRES_PASSWORD: conference_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: ab-conference-web
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  postgres_data:
