version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ab-conference-db
    environment:
      POSTGRES_DB: conference_manager
      POSTGRES_USER: conference_user
      POSTGRES_PASSWORD: conference_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: ab-conference-backend
    ports:
      - "8081:8080"
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    container_name: ab-conference-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
